# fly.toml app configuration file generated for balancebot on 2023-12-01T23:27:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "balancebot"
primary_region = "otp"

[processes]
app = "node ./build/Bot.js"

[build.args]
NODE_ENV = "production"

[env]
  PORT = "8080"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
